// pages/terms.tsx
import Layout from "../components/Layout";

const Terms: React.FC = () => (
  <Layout title="Terms of Service | Hubhop by Mobiflight">
    <div className="container mx-auto min-h-screen px-2 mb-3 text-justify md:mt-10">
      <h1 className="mb-3 text-4xl">Impressum / Terms</h1>
      <h2>Angaben gemäß § 5 TMG:</h2>
      <p>
        Sebastian Möbius
        <br />
        MobiFlight
      </p>
      <p>
        Schneiderbäumlesweg 3<br />
        71336 Waiblingen
      </p>
      <h2>Kontakt:</h2>
      <table>
        <tbody>
          <tr>
            <td>Telefon:</td>
            <td>
              07151 /&nbsp;<span>2728457</span>
            </td>
          </tr>
          <tr>
            <td>E-Mail:</td>
            <td>
              &#105;&#x6E;&#x66;&#111;&#x40;&#x6D;&#x6F;&#x62;&#105;&#102;&#x6C;&#105;&#103;&#x68;&#x74;&#x2E;&#99;&#111;&#x6D;
            </td>
          </tr>
        </tbody>
      </table>
      <h2>Umsatzsteuer-ID:</h2>
      <p>
        Umsatzsteuer-Identifikationsnummer gemäß §27 a Umsatzsteuergesetz:
        <br />
        90283/00436
      </p>
      <br />
      <h1 className="mb-3 text-4xl">Haftungsausschluss (Disclaimer)</h1>
      <p>
        <strong className="text-xl font-bold">Haftung für Inhalte</strong>
      </p>
      <p>
        Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf
        diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8
        bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet,
        übermittelte oder gespeicherte fremde Informationen zu überwachen oder
        nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit
        hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von
        Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt.
        Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der
        Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von
        entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend
        entfernen.
      </p>
      <p>
        <strong className="text-xl font-bold">Haftung für Links</strong>
      </p>
      <p>
        Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren
        Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden
        Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten
        Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten
        verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der
        Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte
        waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente
        inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete
        Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden
        von Rechtsverletzungen werden wir derartige Links umgehend entfernen.
      </p>
      <p>
        <strong className="text-xl font-bold">Urheberrecht</strong>
      </p>
      <p>
        Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen
        Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung,
        Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der
        Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des
        jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite
        sind nur für den privaten, nicht kommerziellen Gebrauch gestattet.
        Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden,
        werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte
        Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine
        Urheberrechtsverletzung aufmerksam werden, bitten wir um einen
        entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden
        wir derartige Inhalte umgehend entfernen.
      </p>
    </div>
  </Layout>
);

export default Terms;

// src/views/Terms.vue
<template>
  <div class="container min-h-screen mx-auto px-2 md:mt-10 -mt-10 mb-10 text-left">
    <h1>Impressum / Terms</h1>
    <h2>Angaben gemäß § 5 TMG:</h2>
    <p>
      Sebastian Möbius<br />
      MobiFlight
    </p>
    <p>
      Schneiderbäumlesweg 3<br />
      71336 Waiblingen
    </p>
    <h2>Kontakt:</h2>
    <table>
      <tbody>
        <tr>
          <td>Telefon:</td>
          <td>07151 /&nbsp;<span>2728457</span></td>
        </tr>
        <tr>
          <td>E-Mail:</td>
          <td>
            &#105;&#x6E;&#x66;&#111;&#x40;&#x6D;&#x6F;&#x62;&#105;&#102;&#x6C;&#105;&#103;&#x68;&#x74;&#x2E;&#99;&#111;&#x6D;
          </td>
        </tr>
      </tbody>
    </table>
    <h2>Umsatzsteuer-ID:</h2>
    <p>
      Umsatzsteuer-Identifikationsnummer gemäß §27 a Umsatzsteuergesetz:<br />
      90283/00436
    </p>
    <h1>Haftungsausschluss (Disclaimer)</h1>
    <p><strong>Haftung für Inhalte</strong></p>
    <p>
      Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf
      diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis
      10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet,
      übermittelte oder gespeicherte fremde Informationen zu überwachen oder
      nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit
      hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von
      Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt.
      Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis
      einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von
      entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend
      entfernen.
    </p>
    <p><strong>Haftung für Links</strong></p>
    <p>
      Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren
      Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden
      Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten
      Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten
      verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung
      auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum
      Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche
      Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte
      einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von
      Rechtsverletzungen werden wir derartige Links umgehend entfernen.
    </p>
    <p><strong>Urheberrecht</strong></p>
    <p>
      Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen
      Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung,
      Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen
      des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen
      Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den
      privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf
      dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte
      Dritter beachtet. Insbesondere werden Inhalte Dritter als solche
      gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung
      aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei
      Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend
      entfernen.
    </p>
  </div>
</template>
